title: Dr. Sonu Sharma
tagline: Research Guide
email: info@drsonusharma.com
description: >-
  Dr. Sonu Sharma is a Ph.D. in Mechanical Engineering with research interest in CFD with Open-Source tools like FreeCAD, Salome, and OpenFOAM.
baseurl: ""
url: "https://drsonusharma.com"
show_excerpts: false
author: "Dr. Sonu Sharma"

facebook_username: drssphd
linkedin_username: drssphd
twitter_username: drssphd
youtube_username: UCjgNiSw-EdoAJXEyXeZANGw
youtube_channel_name: drssphd
rss: rss

header_pages:
- profile.md
- courses.md
- blog.md
- contact.md
- legal.md

paginate: 5
paginate_path: "/posts/page:num/"

theme: minima

google_analytics: UA-217776738-1
permalink: /:title

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate

exclude:
   - .sass-cache/
   - .jekyll-cache/
   - gemfiles/
   - Gemfile
   - Gemfile.lock
   - node_modules/
   - vendor/bundle/
   - vendor/cache/
   - vendor/gems/
   - vendor/ruby/
